### ISSUE TITLE
Typing becomes slow 

### ISSUE THREAD

**Issue by jhautefeuille** [skraus-dev/cherryrgb-rs#47]
**Describe the bug**
The program works, but it makes it impossible to use the keyboard because typing becomes slow.

**Version**
(https://github.com/skraus-dev/cherryrgb-rs/commit/35e464eabb6dbfda028b05e2ccf3572a43af1aa1)

**To Reproduce**
`cherryrgb_cli --product-id 223 -b high animation fire fast ff1100&`

**Additional context**
 - OS: PopOS 22.04 LTS
 - Architecture: amd64
 - Keyboard: Bus 001 Device 021: ID 046a:00df Cherry GmbH CHERRY Keyboard

**Comment by felfert** [comment]
Most likely a side effect of the firmware bug described in #22 and #37
Since version 2.5, there is a workaround: Follow [these](https://github.com/skraus-dev/cherryrgb-rs/blob/master/docs/UHID-driver.md) instructions, then use `cherryrgb_ncli` instead of `cherryrgb_cli`.

**Comment by jhautefeuille** [comment]
Thank you, it's ok now with systemd service configuration.
